name: CI

on:
  push:
    branches:
    - '*'
    paths:
    - '**test.yml'
    - '**.rkt'
    - '**.scrbl'
  pull_request:
    branches:
    - '*'
    paths:
    - '**.rkt'
    - '**.scrbl'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: "Build on Racket '${{ matrix.racket-version }}' (${{ matrix.racket-variant }})"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        racket-version: ["8.1", "8.2", "current"]
        racket-variant: ["BC", "CS"]
    steps:
      - uses: actions/checkout@v2
      - name: Cache installed packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/racket
            ~/.local/share/racket
          key: ${{ runner.os }}-primes
      - uses: Bogdanp/setup-racket@v1.6
        with:
          architecture: x64
          distribution: minimal
          variant: ${{ matrix.racket-variant }}
          version: ${{ matrix.racket-version }}
      - name: Installing k and its dependencies
        run: raco pkg install --skip-installed --no-docs --auto --name k
      - name: Compiling k and building its docs
        run: raco setup --check-pkg-deps --unused-pkg-deps k
      - name: Testing k
        run: raco test -x -p k
